### PR TITLE
Fix issue where message variable is overwritten with the hostname

### PR DESCRIPTION
**Pull request by GavinEke**

### CODE REVIEW

**Comment by GavinEke** [comment]
This needs more work, it fixed the subdirectories are now included but query strings are removed

**Review by smck83 — APPROVED** [review]
tested and appears to work now. thanks

**Comment by smck83** [comment]
changed logic for handling of ALLOWED_HOSTNAMES

**Comment by smck83** [comment]
Special characters cannot be sent via GET request into a web endpoint. Instead URL encode breaking characters; 

e.g. 

````
%23 instead of #
%26 instead of &
````

**Pull request merged**
